version: '3.8'
name: zapato-project
#Multiples contenedores que la aplicacion requiere
services:
  mysqldb:
    image: mysql:5.7
    volumes:
      - $DATA_LOCA_ROUTE:$DATA_DOKCER_ROUTE
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE = $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT